# coding: utf8
Alimentos = (
    (1, 1, '', '', '', "Calor", "Kg."),
    (2, 2, "PAN Y BOLLERIA", '', '', "Calor", "Kg."),
    (3, 3, "CAFÉS E INFUSIONES", '', '', "Calor", "Kg."),
    (4, 4, "CEREALES DE DESAYUNO", '', '', "Calor", "Kg."),
    (6, 6, "CHOCOLATES, BOMBONES, CACAO", '', '', "Calor", "Kg."),
    (7, 7, "CONFITERIA + MERMELADAS", '', '', "Calor", "Kg."),
    (8, 8, '', '', '', "Calor", "Kg."),
    (9, 9, "LECHE", '', '', "Calor", "L."),
    (10, 10, "HARINA", '', '', "Calor", "Kg."),
    (11, 11, "ARROZ, PASTAS", '', '', "Calor", "Kg."),
    (12, 12, "FRUTOS SECOS, LEGUMBRES", '', '', "Calor", "Kg."),
    (13, 13, '', '', '', "Calor", "Kg."),
    (14, 14, "SALSAS Y CONDIMENTOS", '', '', "Calor", "Kg."),
    (17, 17, "ACEITE", '', '', "Calor", "L."),
    (19, 19, "AZUCAR", '', '', "Calor", "Kg."),
    (20, 20, '', '', '', "Calor", "Kg."),
    (21, 21, "VEGETALES EN CONSERVA, (+ tomate frito, triturado, en conserva)", '', '', "Calor", "Kg."),
    (22, 22, "PESCADO", '', '', "Calor", "Kg."),
    (23, 23, "PATÉ", '', '', "Calor", "Kg."),
    (24, 24, "PLATOS PREPARADOS,SOPAS, PURÉS", '', '', "Calor", "Kg."),
    (25, 25, "ALIMENTOS INFANTILES", '', '', "Calor", "Kg."),
    (28, 28, "BEBIDAS, REFRESCOS", '', '', "Calor", "L."),
    (30, 30, '', '', '', "Frío", "Kg."),
    (31, 31, '', '', '', "Frío", "Kg."),
    (32, 32, '', '', '', "Frío", "Kg."),
    (33, 33, '', '', '', "Frío", "Kg."),
    (34, 34, '', '', '', "Calor", "Kg."),
    (35, 35, '', '', '', "Frío", "Kg."),
    (43, 43, "HUEVOS", '', '', "Calor", "Kg."),
    (44, 44, '', '', '', "Calor", "Kg."),
    (45, 45, "VERDURA, HORTALIZAS, FRUTA", '', '', "Frío", "Kg."),
    (46, 46, "CARNES", '', '', "Frío", "Kg."),
    (49, 49, '', '', '', "Frío", "Kg."),
    (51, 51, "PRODUCTOS DE LIMPIEZA", '', '', "Calor", "Kg."),
    (67, 67, '', '', '', "Calor", "Kg."),
    (99, 99, "PRODUCTOS VARIOS", '', '', "Calor", "Kg."),
    (101, 0, "ALIMENTOS NO CATALOGADOS", '', '', "Calor", "Kg."),
    (102, 8, "PRODUCTOS LACTEOS", '', '', "Frío", "Kg.")
)
