# coding: utf8
Provincias=(
(1, 'Álava', 'alava', 'ALV','01'),
(2, 'Castellón', 'castellon', 'CAS','12'),
(3, 'León', 'leon', 'LEO','24'),
(4, 'Salamanca', 'salamanca', 'SAL','37'),
(5, 'Albacete', 'albacete', 'ABC','02'),
(6, 'Ceuta', 'ceuta', 'CEU','51'),
(7, 'Lérida', 'lleida', 'LLE','25'),
(8, 'Segovia', 'segovia', 'SGV','40'),
(9, 'Alicante', 'alicante', 'ALA','03'),
(10, 'Ciudad Real', 'ciudad-real', 'CRE','13'),
(11, 'Lugo', 'lugo', 'LUG','27'),
(12, 'Sevilla', 'sevilla', 'SVL','41'),
(13, 'Almería', 'almeria', 'ALM','04'),
(14, 'Córdoba', 'cordoba', 'CBA','14'),
(15, 'Madrid', 'madrid', 'MAD','28'),
(16, 'Soria', 'soria', 'SOR','42'),
(17, 'Asturias', 'asturias', 'AST','33'),
(18, 'La Coruña', 'coruna', 'LCO','15'),
(19, 'Málaga', 'malaga', 'MAL','29'),
(20, 'Tarragona', 'tarragona', 'TRN','43'),
(21, 'Ávila', 'avila', 'AVL','05'),
(22, 'Cuenca', 'cuenca', 'CNC','16'),
(23, 'Melilla', 'melilla', 'MEL','52'),
(24, 'S.C. Tenerife', 'tenerife', 'SCT','38'),
(25, 'Badajoz', 'badajoz', 'BDJ','06'),
(26, 'Gerona', 'girona', 'GIR','17'),
(27, 'Murcia', 'murcia', 'MUR','30'),
(28, 'Teruel', 'teruel', 'TER','44'),
(29, 'Baleares', 'baleares', 'BAL','07'),
(30, 'Granada', 'granada', 'GND','18'),
(31, 'Navarra', 'navarra', 'NVR','31'),
(32, 'Toledo', 'toledo', 'TOL','45'),
(33, 'Barcelona', 'barcelona', 'BCN','08'),
(34, 'Guadalajara', 'guadalajara', 'GLJ','19'),
(35, 'Ourense', 'ourense', 'OUR','32'),
(36, 'Valencia', 'valencia', 'VAL','46'),
(37, 'Burgos', 'burgos', 'BRG','09'),
(38, 'Guipúzcoa', 'guipuzcoa', 'GPZ','20'),
(39, 'Palencia', 'palencia', 'PAL','34'),
(40, 'Valladolid', 'valladolid', 'VLL','47'),
(41, 'Cáceres', 'caceres', 'CAC','10'),
(42, 'Huelva', 'huelva', 'HLV','21'),
(43, 'Las Palmas', 'palmas', 'LPA','35'),
(44, 'Vizcaya', 'vizcaya', 'VZC','48'),
(45, 'Cádiz', 'cadiz', 'CDZ','11'),
(46, 'Huesca', 'huesca', 'HSC','22'),
(47, 'Pontevedra', 'pontevedra', 'PNV','36'),
(48, 'Zamora', 'zamora', 'ZAM','49'),
(49, 'Cantabria', 'cantabria', 'CTB','39'),
(50, 'Jaén', 'jaen', 'JAE','23'),
(51, 'La Rioja', 'rioja', 'LRJ','26'),
(52, 'Zaragoza', 'zaragoza', 'ZAR','50')
)
